name: namegen
version: 1.0.0
summary: Name generator for writers
description: |
  Namegen is a name generator for writers.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

apps:
  namegen:
    plugs:
      - x11
      - unity7
      - desktop
      - desktop-legacy
      - wayland
      - gsettings
    command: usr/bin/namegen
    extensions: [gnome-3-28]
parts:
  namegen:
    source-type: local
    source: .
    plugin: make
    build-packages:
      - desktop-file-utils
      - gettext
      - gnome-common
      - appstream-util
      - gnome-pkg-tools
      - intltool
      - libglib2.0-dev
      - libgtk-3-dev
      - libxml2-dev
